# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAviso(object):
    def setupUi(self, DialogAviso):
        DialogAviso.setObjectName("DialogAviso")
        DialogAviso.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/warning/img/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogAviso.setWindowIcon(icon)
        DialogAviso.setStyleSheet("background-color:#495371;color:white")

        self.retranslateUi(DialogAviso)
        QtCore.QMetaObject.connectSlotsByName(DialogAviso)

    def retranslateUi(self, DialogAviso):
        _translate = QtCore.QCoreApplication.translate
        DialogAviso.setWindowTitle(_translate("DialogAviso", "AVISO"))
import recursos_rc
